// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxy$0 from "../proxy/models.js";

/**
 * AgentModels agent 分组内的一组模型
 */
export class AgentModels {
    "upstream": string;
    "models": string[];

    /** Creates a new AgentModels instance. */
    constructor($$source: Partial<AgentModels> = {}) {
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentModels instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentModels {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField1_0($$parsedSource["models"]);
        }
        return new AgentModels($$parsedSource as Partial<AgentModels>);
    }
}

/**
 * Config 代理运行配置
 */
export class Config {
    /**
     * "auto" | "manual" | "ua"
     */
    "mode": string;

    /**
     * auto 模式优先级链
     */
    "autoChain": AgentModels[];

    /**
     * 手动模式下模型的降级链
     */
    "manualFallbacks": { [_ in string]?: proxy$0.ModelRef[] };

    /**
     * auto/manual 全局兜底
     */
    "globalFallback": proxy$0.ModelRef;

    /**
     * auto/manual 模式下 UA 叠加层开关
     */
    "uaRoutingEnabled": boolean;

    /**
     * UA 路由规则
     */
    "uaRules": UARule[];

    /**
     * ua 模式全局兜底
     */
    "uaGlobalFallback": proxy$0.ModelRef;

    /**
     * 代理监听端口
     */
    "port": number;

    /**
     * 客户端接入密钥（AuthEnabled=true 时严格校验）
     */
    "apiKey": string;

    /**
     * 是否要求客户端携带 apiKey；默认 true，关闭后网关不鉴权
     */
    "authEnabled": boolean;

    /**
     * 登录系统时自动启动（静默到托盘，以 --tray 启动）
     */
    "autoStart": boolean;

    /**
     * 自动升级配置
     */
    "update": UpdateConfig;

    /**
     * 控制台日志落地文件配置
     */
    "logFile": LogFileConfig;

    /**
     * 已保存的运行模式方案
     */
    "presets": Preset[];

    /**
     * 当前激活方案名（仅 UI 提示；偏离后置空 = 自定义）
     */
    "activePreset": string;

    /**
     * 供应商配置相关偏好
     */
    "provider": ProviderSettings;

    /**
     * 各上游启用开关（key=upstream/provider id，缺省视为启用）
     */
    "upstreams"?: { [_ in string]?: UpstreamSettings };

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("autoChain" in $$source)) {
            this["autoChain"] = [];
        }
        if (!("manualFallbacks" in $$source)) {
            this["manualFallbacks"] = {};
        }
        if (!("globalFallback" in $$source)) {
            this["globalFallback"] = (new proxy$0.ModelRef());
        }
        if (!("uaRoutingEnabled" in $$source)) {
            this["uaRoutingEnabled"] = false;
        }
        if (!("uaRules" in $$source)) {
            this["uaRules"] = [];
        }
        if (!("uaGlobalFallback" in $$source)) {
            this["uaGlobalFallback"] = (new proxy$0.ModelRef());
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("authEnabled" in $$source)) {
            this["authEnabled"] = false;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("update" in $$source)) {
            this["update"] = (new UpdateConfig());
        }
        if (!("logFile" in $$source)) {
            this["logFile"] = (new LogFileConfig());
        }
        if (!("presets" in $$source)) {
            this["presets"] = [];
        }
        if (!("activePreset" in $$source)) {
            this["activePreset"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = (new ProviderSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType3;
        const $$createField5_0 = $$createType7;
        const $$createField6_0 = $$createType3;
        const $$createField11_0 = $$createType8;
        const $$createField12_0 = $$createType9;
        const $$createField13_0 = $$createType11;
        const $$createField15_0 = $$createType12;
        const $$createField16_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("autoChain" in $$parsedSource) {
            $$parsedSource["autoChain"] = $$createField1_0($$parsedSource["autoChain"]);
        }
        if ("manualFallbacks" in $$parsedSource) {
            $$parsedSource["manualFallbacks"] = $$createField2_0($$parsedSource["manualFallbacks"]);
        }
        if ("globalFallback" in $$parsedSource) {
            $$parsedSource["globalFallback"] = $$createField3_0($$parsedSource["globalFallback"]);
        }
        if ("uaRules" in $$parsedSource) {
            $$parsedSource["uaRules"] = $$createField5_0($$parsedSource["uaRules"]);
        }
        if ("uaGlobalFallback" in $$parsedSource) {
            $$parsedSource["uaGlobalFallback"] = $$createField6_0($$parsedSource["uaGlobalFallback"]);
        }
        if ("update" in $$parsedSource) {
            $$parsedSource["update"] = $$createField11_0($$parsedSource["update"]);
        }
        if ("logFile" in $$parsedSource) {
            $$parsedSource["logFile"] = $$createField12_0($$parsedSource["logFile"]);
        }
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField13_0($$parsedSource["presets"]);
        }
        if ("provider" in $$parsedSource) {
            $$parsedSource["provider"] = $$createField15_0($$parsedSource["provider"]);
        }
        if ("upstreams" in $$parsedSource) {
            $$parsedSource["upstreams"] = $$createField16_0($$parsedSource["upstreams"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * GitHubConfig GitHub Releases 配置
 */
export class GitHubConfig {
    /**
     * GitHub 用户名/组织
     */
    "owner": string;

    /**
     * 仓库名
     */
    "repo": string;

    /**
     * 私有仓库 PAT（公开仓库可空）
     */
    "token": string;

    /** Creates a new GitHubConfig instance. */
    constructor($$source: Partial<GitHubConfig> = {}) {
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("repo" in $$source)) {
            this["repo"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubConfig($$parsedSource as Partial<GitHubConfig>);
    }
}

/**
 * LogFileConfig 控制台日志落地到文件的配置
 */
export class LogFileConfig {
    /**
     * 是否把控制台日志同时写入文件（默认开启）
     */
    "enabled": boolean;

    /** Creates a new LogFileConfig instance. */
    constructor($$source: Partial<LogFileConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFileConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LogFileConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFileConfig($$parsedSource as Partial<LogFileConfig>);
    }
}

/**
 * Preset 运行模式方案快照
 * 只含降级链相关字段，不含 port/apiKey/update —— 那些是环境配置，
 * 不应随方案切换而变（apiKey 变了会让已接入的客户端 401）
 */
export class Preset {
    "name": string;
    "mode": string;
    "autoChain": AgentModels[];
    "manualFallbacks": { [_ in string]?: proxy$0.ModelRef[] };
    "globalFallback": proxy$0.ModelRef;
    "uaRoutingEnabled": boolean;
    "uaRules": UARule[];
    "uaGlobalFallback": proxy$0.ModelRef;

    /** Creates a new Preset instance. */
    constructor($$source: Partial<Preset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("autoChain" in $$source)) {
            this["autoChain"] = [];
        }
        if (!("manualFallbacks" in $$source)) {
            this["manualFallbacks"] = {};
        }
        if (!("globalFallback" in $$source)) {
            this["globalFallback"] = (new proxy$0.ModelRef());
        }
        if (!("uaRoutingEnabled" in $$source)) {
            this["uaRoutingEnabled"] = false;
        }
        if (!("uaRules" in $$source)) {
            this["uaRules"] = [];
        }
        if (!("uaGlobalFallback" in $$source)) {
            this["uaGlobalFallback"] = (new proxy$0.ModelRef());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preset instance from a string or object.
     */
    static createFrom($$source: any = {}): Preset {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType3;
        const $$createField6_0 = $$createType7;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("autoChain" in $$parsedSource) {
            $$parsedSource["autoChain"] = $$createField2_0($$parsedSource["autoChain"]);
        }
        if ("manualFallbacks" in $$parsedSource) {
            $$parsedSource["manualFallbacks"] = $$createField3_0($$parsedSource["manualFallbacks"]);
        }
        if ("globalFallback" in $$parsedSource) {
            $$parsedSource["globalFallback"] = $$createField4_0($$parsedSource["globalFallback"]);
        }
        if ("uaRules" in $$parsedSource) {
            $$parsedSource["uaRules"] = $$createField6_0($$parsedSource["uaRules"]);
        }
        if ("uaGlobalFallback" in $$parsedSource) {
            $$parsedSource["uaGlobalFallback"] = $$createField7_0($$parsedSource["uaGlobalFallback"]);
        }
        return new Preset($$parsedSource as Partial<Preset>);
    }
}

/**
 * ProviderSettings 供应商功能偏好
 */
export class ProviderSettings {
    /**
     * AutoBenchmarkOnEdit 进入供应商编辑时自动拉取模型并批量测评
     */
    "autoBenchmarkOnEdit": boolean;

    /**
     * IdleAutoLock 闲置时自动锁定供应商界面（默认开启）
     */
    "idleAutoLock": boolean;

    /** Creates a new ProviderSettings instance. */
    constructor($$source: Partial<ProviderSettings> = {}) {
        if (!("autoBenchmarkOnEdit" in $$source)) {
            this["autoBenchmarkOnEdit"] = false;
        }
        if (!("idleAutoLock" in $$source)) {
            this["idleAutoLock"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderSettings($$parsedSource as Partial<ProviderSettings>);
    }
}

/**
 * UAModelMap 请求模型 -> 目标上游模型的映射
 */
export class UAModelMap {
    "requestedModel": string;
    "target": proxy$0.ModelRef;

    /** Creates a new UAModelMap instance. */
    constructor($$source: Partial<UAModelMap> = {}) {
        if (!("requestedModel" in $$source)) {
            this["requestedModel"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = (new proxy$0.ModelRef());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UAModelMap instance from a string or object.
     */
    static createFrom($$source: any = {}): UAModelMap {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField1_0($$parsedSource["target"]);
        }
        return new UAModelMap($$parsedSource as Partial<UAModelMap>);
    }
}

/**
 * UARule 单条 User-Agent 路由规则
 */
export class UARule {
    "id": string;
    "name": string;
    "pattern": string;
    "enabled": boolean;
    "mappings": UAModelMap[];

    /**
     * DefaultTarget 规则级默认目标：UA 命中但请求模型未命中任何 mapping 时，
     * 整个请求路由到该目标（请求模型 id 原样透传给上游，由上游/代理处理）。
     * 留空则回退到 UA 全局兜底（uaGlobalFallback）/正常降级链。
     * 这是「cc-switch 式」的免维护方案——无需为每个客户端枚举请求模型列表。
     */
    "defaultTarget"?: proxy$0.ModelRef;

    /** Creates a new UARule instance. */
    constructor($$source: Partial<UARule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("mappings" in $$source)) {
            this["mappings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UARule instance from a string or object.
     */
    static createFrom($$source: any = {}): UARule {
        const $$createField4_0 = $$createType16;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mappings" in $$parsedSource) {
            $$parsedSource["mappings"] = $$createField4_0($$parsedSource["mappings"]);
        }
        if ("defaultTarget" in $$parsedSource) {
            $$parsedSource["defaultTarget"] = $$createField5_0($$parsedSource["defaultTarget"]);
        }
        return new UARule($$parsedSource as Partial<UARule>);
    }
}

/**
 * UpdateConfig 自动升级配置
 */
export class UpdateConfig {
    /**
     * 是否启用自动升级检查
     */
    "enabled": boolean;

    /**
     * "github" | "custom"（默认 github）
     */
    "provider": string;

    /**
     * GitHub Releases 配置
     */
    "github": GitHubConfig;

    /**
     * 自定义检查地址（优先于 github）
     */
    "updateUrl": string;

    /**
     * "stable" | "beta"（默认 stable）
     */
    "channel": string;

    /**
     * 用户跳过的版本号，不再提示
     */
    "skippedVersion": string;

    /** Creates a new UpdateConfig instance. */
    constructor($$source: Partial<UpdateConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("github" in $$source)) {
            this["github"] = (new GitHubConfig());
        }
        if (!("updateUrl" in $$source)) {
            this["updateUrl"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }
        if (!("skippedVersion" in $$source)) {
            this["skippedVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateConfig {
        const $$createField2_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("github" in $$parsedSource) {
            $$parsedSource["github"] = $$createField2_0($$parsedSource["github"]);
        }
        return new UpdateConfig($$parsedSource as Partial<UpdateConfig>);
    }
}

/**
 * UpstreamSettings 单个上游的开关配置
 */
export class UpstreamSettings {
    /**
     * Enabled 该上游是否启用；禁用时其下所有模型在调用时被直接跳过（全局生效）
     */
    "enabled": boolean;

    /** Creates a new UpstreamSettings instance. */
    constructor($$source: Partial<UpstreamSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpstreamSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UpstreamSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpstreamSettings($$parsedSource as Partial<UpstreamSettings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AgentModels.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = proxy$0.ModelRef.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = UARule.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = UpdateConfig.createFrom;
const $$createType9 = LogFileConfig.createFrom;
const $$createType10 = Preset.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ProviderSettings.createFrom;
const $$createType13 = UpstreamSettings.createFrom;
const $$createType14 = $Create.Map($Create.Any, $$createType13);
const $$createType15 = UAModelMap.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = GitHubConfig.createFrom;
