// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService 配置管理服务（暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyPreset 应用方案（立即生效）
 */
export function ApplyPreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(2103519218, name);
}

/**
 * ClearActivePreset 清除当前激活方案标记（切换到"自定义"状态，配置内容不变）
 */
export function ClearActivePreset(): $CancellablePromise<void> {
    return $Call.ByID(3919344305);
}

/**
 * DeletePreset 删除方案
 */
export function DeletePreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(2521626179, name);
}

/**
 * GetAutoStart 返回当前是否已开启开机自启（以系统实际注册状态为准，防止配置与系统不一致）。
 */
export function GetAutoStart(): $CancellablePromise<boolean> {
    return $Call.ByID(1573953834);
}

/**
 * GetAvailableModels 返回各 upstream 可选模型（实时合并 + 缓存 10 分钟）
 * 若 core 未注入，回退本地白名单
 */
export function GetAvailableModels(): $CancellablePromise<$models.UpstreamModels[]> {
    return $Call.ByID(572909798).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetConfig 获取当前配置（克隆，前端可安全读取）
 */
export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(4069551403).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetModelsByUASource 查询某个 source 历史请求过的模型（按次数降序）
 */
export function GetModelsByUASource(sourceName: string): $CancellablePromise<db$0.SourceModelStat[]> {
    return $Call.ByID(3300743737, sourceName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetUASources 列出所有已知的请求来源（User-Agent），用于 UA 路由配置辅助
 */
export function GetUASources(): $CancellablePromise<db$0.SourceInfo[]> {
    return $Call.ByID(1434189675).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * InvalidateModelCache 清空模型列表缓存（供应商增删/模型变化时调用）
 */
export function InvalidateModelCache(): $CancellablePromise<void> {
    return $Call.ByID(503319539);
}

/**
 * ReconcileAutoStart 启动时调用：让系统自启状态与配置一致（配置优先）。
 * 用当前可执行路径重新注册，修复「程序移动位置后旧自启项失效」。
 */
export function ReconcileAutoStart(): $CancellablePromise<void> {
    return $Call.ByID(3365035890);
}

/**
 * RefreshModels 强制刷新模型列表（忽略缓存）
 * 同时刷新内置上游的持久化目录，让 /v1/models 和路由层也拿到最新模型
 */
export function RefreshModels(): $CancellablePromise<$models.UpstreamModels[]> {
    return $Call.ByID(2657703844).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RenamePreset 重命名方案
 */
export function RenamePreset(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(3958134766, oldName, newName);
}

/**
 * ResetConfig 重置为默认配置，端口变化时重启代理
 */
export function ResetConfig(): $CancellablePromise<void> {
    return $Call.ByID(287043192);
}

/**
 * SaveConfig 保存配置（校验 + 写盘 + 热加载），端口变化时重启代理
 */
export function SaveConfig(cfg: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(3633172612, cfg);
}

/**
 * SavePreset 把当前运行模式配置存为方案；同名覆盖
 */
export function SavePreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(1764980289, name);
}

/**
 * SetAutoStart 切换开机自启，并把结果写回配置。
 */
export function SetAutoStart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1275086038, enabled);
}

// Private type creation functions
const $$createType0 = $models.UpstreamModels.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = config$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = db$0.SourceModelStat.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = db$0.SourceInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
