// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService 请求日志服务（暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxy$0 from "../proxy/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearLogs 清空内存日志 + 数据库日志
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1803107935);
}

/**
 * GetLogDates 列出所有有日志的日期（倒序）
 */
export function GetLogDates(): $CancellablePromise<string[]> {
    return $Call.ByID(3417159050).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetLogStats 获取日志统计（进程内累计，重启归零；仪表盘总览用）
 */
export function GetLogStats(): $CancellablePromise<$models.LogStats | null> {
    return $Call.ByID(1185748336).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLogsByRange 按日期范围查询日志，从 SQLite 读，倒序
 * 日期格式 "YYYY-MM-DD"
 */
export function GetLogsByRange(startDate: string, endDate: string, limit: number): $CancellablePromise<(proxy$0.LogEntry | null)[]> {
    return $Call.ByID(2612445780, startDate, endDate, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetRecentLogs 获取最近 N 条日志（内存 buffer，倒序，最新在前）
 */
export function GetRecentLogs(count: number): $CancellablePromise<(proxy$0.LogEntry | null)[]> {
    return $Call.ByID(1557978037, count).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTodaySpeed 暴露给前端：今日输出速率统计（优先从 db 查）
 */
export function GetTodaySpeed(): $CancellablePromise<$models.SpeedStats | null> {
    return $Call.ByID(1843081073).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetTodaySummary 今日总消耗 token 和费用（优先从 db 查，回退到文件扫描）
 */
export function GetTodaySummary(): $CancellablePromise<$models.TodaySummary | null> {
    return $Call.ByID(745909738).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetUsageStats 暴露给前端的统计方法（优先从 db 查，回退到文件扫描）
 */
export function GetUsageStats(startDate: string, endDate: string): $CancellablePromise<$models.UsageStats | null> {
    return $Call.ByID(1672045915, startDate, endDate).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetUsageTrend 暴露给前端的趋势方法（优先从 db 查，回退到文件扫描）
 */
export function GetUsageTrend(startDate: string, endDate: string, granularity: string): $CancellablePromise<$models.UsageTrend | null> {
    return $Call.ByID(1604637487, startDate, endDate, granularity).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * LogCountsByRange 按日期范围统计各状态日志数（从数据库读取，重启后仍准确）
 * 返回 total/success/error/authError/fallback 计数，供日志页筛选按钮显示。
 */
export function LogCountsByRange(startDate: string, endDate: string): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(1465699747, startDate, endDate).then(($result: any) => {
        return $$createType14($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.LogStats.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = proxy$0.LogEntry.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = db$0.SpeedStats.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.TodaySummary.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.UsageStats.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = db$0.UsageTrend.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
