// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as creds$0 from "../creds/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxy$0 from "../proxy/models.js";

/**
 * AgentDetail agent 工具详情（前端 SetupGuide 渲染用）
 */
export class AgentDetail {
    "name": string;
    "upstream": string;

    /**
     * "gui" | "cli"
     */
    "type": string;
    "desc": string;
    "downloadUrl": string;
    "installCmd": string;
    "loginCmd": string;
    "loginUrl": string;
    "installed": boolean;
    "valid": boolean;

    /** Creates a new AgentDetail instance. */
    constructor($$source: Partial<AgentDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            this["downloadUrl"] = "";
        }
        if (!("installCmd" in $$source)) {
            this["installCmd"] = "";
        }
        if (!("loginCmd" in $$source)) {
            this["loginCmd"] = "";
        }
        if (!("loginUrl" in $$source)) {
            this["loginUrl"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentDetail($$parsedSource as Partial<AgentDetail>);
    }
}

/**
 * AllCredStatus 四上游 + 免费 API 凭据状态
 */
export class AllCredStatus {
    "joycode": creds$0.CredStatusInfo | null;
    "deveco": creds$0.CredStatusInfo | null;
    "opencode": creds$0.CredStatusInfo | null;
    "workbuddy": creds$0.CredStatusInfo | null;

    /**
     * 免费 API 供应商（动态）
     */
    "providerAPIs"?: { [_ in string]?: creds$0.CredStatusInfo | null };

    /** Creates a new AllCredStatus instance. */
    constructor($$source: Partial<AllCredStatus> = {}) {
        if (!("joycode" in $$source)) {
            this["joycode"] = null;
        }
        if (!("deveco" in $$source)) {
            this["deveco"] = null;
        }
        if (!("opencode" in $$source)) {
            this["opencode"] = null;
        }
        if (!("workbuddy" in $$source)) {
            this["workbuddy"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AllCredStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AllCredStatus {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("joycode" in $$parsedSource) {
            $$parsedSource["joycode"] = $$createField0_0($$parsedSource["joycode"]);
        }
        if ("deveco" in $$parsedSource) {
            $$parsedSource["deveco"] = $$createField1_0($$parsedSource["deveco"]);
        }
        if ("opencode" in $$parsedSource) {
            $$parsedSource["opencode"] = $$createField2_0($$parsedSource["opencode"]);
        }
        if ("workbuddy" in $$parsedSource) {
            $$parsedSource["workbuddy"] = $$createField3_0($$parsedSource["workbuddy"]);
        }
        if ("providerAPIs" in $$parsedSource) {
            $$parsedSource["providerAPIs"] = $$createField4_0($$parsedSource["providerAPIs"]);
        }
        return new AllCredStatus($$parsedSource as Partial<AllCredStatus>);
    }
}

/**
 * BenchmarkResult 单个上游模型测评结果
 */
export class BenchmarkResult {
    "upstream": string;
    "upstreamLabel": string;
    "model": string;
    "success": boolean;

    /**
     * 总耗时（端到端）
     */
    "durationMs": number;

    /**
     * 输出 token
     */
    "outputTokens": number;

    /**
     * output_tokens / (duration/1000)
     */
    "tps": number;

    /**
     * 返回文本（供比对）
     */
    "content"?: string;
    "errorMsg"?: string;

    /**
     * 开始时间戳（ms）
     */
    "startedAt": number;

    /** Creates a new BenchmarkResult instance. */
    constructor($$source: Partial<BenchmarkResult> = {}) {
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("upstreamLabel" in $$source)) {
            this["upstreamLabel"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            this["outputTokens"] = 0;
        }
        if (!("tps" in $$source)) {
            this["tps"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BenchmarkResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BenchmarkResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BenchmarkResult($$parsedSource as Partial<BenchmarkResult>);
    }
}

/**
 * BenchmarkTarget 测评目标（上游 + 模型）
 */
export class BenchmarkTarget {
    /**
     * joycode/deveco/opencode/workbuddy
     */
    "upstream": string;

    /**
     * 代理内部 id
     */
    "model": string;

    /** Creates a new BenchmarkTarget instance. */
    constructor($$source: Partial<BenchmarkTarget> = {}) {
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BenchmarkTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): BenchmarkTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BenchmarkTarget($$parsedSource as Partial<BenchmarkTarget>);
    }
}

/**
 * Dashboard 仪表盘聚合数据
 */
export class Dashboard {
    "proxy": proxy$0.ProxyStatus | null;
    "creds": AllCredStatus | null;
    "stats": LogStats | null;
    "recentLogs": (proxy$0.LogEntry | null)[];

    /** Creates a new Dashboard instance. */
    constructor($$source: Partial<Dashboard> = {}) {
        if (!("proxy" in $$source)) {
            this["proxy"] = null;
        }
        if (!("creds" in $$source)) {
            this["creds"] = null;
        }
        if (!("stats" in $$source)) {
            this["stats"] = null;
        }
        if (!("recentLogs" in $$source)) {
            this["recentLogs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dashboard instance from a string or object.
     */
    static createFrom($$source: any = {}): Dashboard {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("proxy" in $$parsedSource) {
            $$parsedSource["proxy"] = $$createField0_0($$parsedSource["proxy"]);
        }
        if ("creds" in $$parsedSource) {
            $$parsedSource["creds"] = $$createField1_0($$parsedSource["creds"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField2_0($$parsedSource["stats"]);
        }
        if ("recentLogs" in $$parsedSource) {
            $$parsedSource["recentLogs"] = $$createField3_0($$parsedSource["recentLogs"]);
        }
        return new Dashboard($$parsedSource as Partial<Dashboard>);
    }
}

/**
 * LogPage 一页日志 + 分页元信息
 */
export class LogPage {
    "logs": (proxy$0.LogEntry | null)[];

    /**
     * 当前范围+状态下的总条数
     */
    "total": number;

    /**
     * 本页起始偏移
     */
    "offset": number;

    /**
     * 每页条数
     */
    "limit": number;

    /** Creates a new LogPage instance. */
    constructor($$source: Partial<LogPage> = {}) {
        if (!("logs" in $$source)) {
            this["logs"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogPage instance from a string or object.
     */
    static createFrom($$source: any = {}): LogPage {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField0_0($$parsedSource["logs"]);
        }
        return new LogPage($$parsedSource as Partial<LogPage>);
    }
}

/**
 * LogStats 日志统计
 */
export class LogStats {
    "total": number;
    "success": number;
    "error": number;
    "authError": number;

    /** Creates a new LogStats instance. */
    constructor($$source: Partial<LogStats> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = 0;
        }
        if (!("authError" in $$source)) {
            this["authError"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStats instance from a string or object.
     */
    static createFrom($$source: any = {}): LogStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogStats($$parsedSource as Partial<LogStats>);
    }
}

/**
 * ModelDetail 模型详情（前端展示用）
 */
export class ModelDetail {
    "id": string;
    "label": string;
    "upstream": string;
    "stream": boolean;
    "context": number;
    "output": number;
    "vision": boolean;
    "toolCall": boolean;
    "reasoning"?: boolean;

    /**
     * 限时免费标识
     */
    "free"?: boolean;

    /**
     * live=接口实时/DB 回读 | local=种子白名单 | free=供应商
     */
    "source"?: string;

    /** Creates a new ModelDetail instance. */
    constructor($$source: Partial<ModelDetail> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("stream" in $$source)) {
            this["stream"] = false;
        }
        if (!("context" in $$source)) {
            this["context"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }
        if (!("vision" in $$source)) {
            this["vision"] = false;
        }
        if (!("toolCall" in $$source)) {
            this["toolCall"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelDetail($$parsedSource as Partial<ModelDetail>);
    }
}

/**
 * ModelOption 模型选项
 */
export class ModelOption {
    "id": string;
    "label": string;
    "context"?: number;
    "output"?: number;
    "stream": boolean;
    "vision"?: boolean;
    "toolCall"?: boolean;
    "reasoning"?: boolean;

    /**
     * 限时免费标识
     */
    "free"?: boolean;

    /** Creates a new ModelOption instance. */
    constructor($$source: Partial<ModelOption> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("stream" in $$source)) {
            this["stream"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelOption instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelOption($$parsedSource as Partial<ModelOption>);
    }
}

/**
 * ModelUsage 模型维度统计
 */
export class ModelUsage {
    /**
     * 实际用到的模型（内部 id，如 provider/<pid>/<mid>）
     */
    "model": string;

    /**
     * 显示名（免费模型会带上供应商名）
     */
    "modelLabel": string;
    "tokens": number;
    "input": number;
    "output": number;
    "cost": number;
    "requests": number;

    /**
     * token 占比 0-100
     */
    "percent": number;

    /** Creates a new ModelUsage instance. */
    constructor($$source: Partial<ModelUsage> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("modelLabel" in $$source)) {
            this["modelLabel"] = "";
        }
        if (!("tokens" in $$source)) {
            this["tokens"] = 0;
        }
        if (!("input" in $$source)) {
            this["input"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }
        if (!("cost" in $$source)) {
            this["cost"] = 0;
        }
        if (!("requests" in $$source)) {
            this["requests"] = 0;
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelUsage($$parsedSource as Partial<ModelUsage>);
    }
}

/**
 * PricingItem 费率项（前端展示用）
 */
export class PricingItem {
    "modelId": string;
    "displayName": string;
    "inputPerMillion": number;
    "outputPerMillion": number;
    "cacheRead": number;
    "cacheCreation": number;

    /** Creates a new PricingItem instance. */
    constructor($$source: Partial<PricingItem> = {}) {
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("inputPerMillion" in $$source)) {
            this["inputPerMillion"] = 0;
        }
        if (!("outputPerMillion" in $$source)) {
            this["outputPerMillion"] = 0;
        }
        if (!("cacheRead" in $$source)) {
            this["cacheRead"] = 0;
        }
        if (!("cacheCreation" in $$source)) {
            this["cacheCreation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PricingItem instance from a string or object.
     */
    static createFrom($$source: any = {}): PricingItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PricingItem($$parsedSource as Partial<PricingItem>);
    }
}

/**
 * ProviderUsage 供应商（上游）维度统计
 */
export class ProviderUsage {
    /**
     * 上游标识 joycode/deveco/.../供应商ID
     */
    "provider": string;

    /**
     * 显示名
     */
    "providerLabel": string;
    "tokens": number;
    "input": number;
    "output": number;
    "cost": number;
    "requests": number;
    "successReqs": number;

    /** Creates a new ProviderUsage instance. */
    constructor($$source: Partial<ProviderUsage> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("providerLabel" in $$source)) {
            this["providerLabel"] = "";
        }
        if (!("tokens" in $$source)) {
            this["tokens"] = 0;
        }
        if (!("input" in $$source)) {
            this["input"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }
        if (!("cost" in $$source)) {
            this["cost"] = 0;
        }
        if (!("requests" in $$source)) {
            this["requests"] = 0;
        }
        if (!("successReqs" in $$source)) {
            this["successReqs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderUsage($$parsedSource as Partial<ProviderUsage>);
    }
}

/**
 * SpeedStats 今日输出速率统计（性能评估）
 */
export const SpeedStats = db$0.SpeedStats;

/**
 * SpeedStats 今日输出速率统计（性能评估）
 */
export type SpeedStats = db$0.SpeedStats;

/**
 * TodaySummary 今日使用概览（首页展示）
 */
export class TodaySummary {
    "tokens": number;
    "cost": number;

    /** Creates a new TodaySummary instance. */
    constructor($$source: Partial<TodaySummary> = {}) {
        if (!("tokens" in $$source)) {
            this["tokens"] = 0;
        }
        if (!("cost" in $$source)) {
            this["cost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TodaySummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TodaySummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TodaySummary($$parsedSource as Partial<TodaySummary>);
    }
}

/**
 * UpstreamModels 单个 upstream 的可选模型
 */
export class UpstreamModels {
    "upstream": string;

    /**
     * "live"（接口实时）| "local"（本地白名单兜底）
     */
    "source": string;
    "models": ModelOption[];

    /** Creates a new UpstreamModels instance. */
    constructor($$source: Partial<UpstreamModels> = {}) {
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpstreamModels instance from a string or object.
     */
    static createFrom($$source: any = {}): UpstreamModels {
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField2_0($$parsedSource["models"]);
        }
        return new UpstreamModels($$parsedSource as Partial<UpstreamModels>);
    }
}

/**
 * UsageStats 使用统计结果
 */
export class UsageStats {
    "startDate": string;
    "endDate": string;
    "totalTokens": number;
    "totalInput": number;
    "totalOutput": number;
    "totalCost": number;
    "totalReqs": number;
    "successReqs": number;
    "byProvider": ProviderUsage[];
    "byModel": ModelUsage[];

    /** Creates a new UsageStats instance. */
    constructor($$source: Partial<UsageStats> = {}) {
        if (!("startDate" in $$source)) {
            this["startDate"] = "";
        }
        if (!("endDate" in $$source)) {
            this["endDate"] = "";
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }
        if (!("totalInput" in $$source)) {
            this["totalInput"] = 0;
        }
        if (!("totalOutput" in $$source)) {
            this["totalOutput"] = 0;
        }
        if (!("totalCost" in $$source)) {
            this["totalCost"] = 0;
        }
        if (!("totalReqs" in $$source)) {
            this["totalReqs"] = 0;
        }
        if (!("successReqs" in $$source)) {
            this["successReqs"] = 0;
        }
        if (!("byProvider" in $$source)) {
            this["byProvider"] = [];
        }
        if (!("byModel" in $$source)) {
            this["byModel"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageStats instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageStats {
        const $$createField8_0 = $$createType15;
        const $$createField9_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("byProvider" in $$parsedSource) {
            $$parsedSource["byProvider"] = $$createField8_0($$parsedSource["byProvider"]);
        }
        if ("byModel" in $$parsedSource) {
            $$parsedSource["byModel"] = $$createField9_0($$parsedSource["byModel"]);
        }
        return new UsageStats($$parsedSource as Partial<UsageStats>);
    }
}

/**
 * UsageTrend 使用趋势结果
 */
export const UsageTrend = db$0.UsageTrend;

/**
 * UsageTrend 使用趋势结果
 */
export type UsageTrend = db$0.UsageTrend;

// Private type creation functions
const $$createType0 = creds$0.CredStatusInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = proxy$0.ProxyStatus.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = AllCredStatus.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = LogStats.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = proxy$0.LogEntry.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ModelOption.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ProviderUsage.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ModelUsage.createFrom;
const $$createType17 = $Create.Array($$createType16);
