// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdaterService 自动升级服务（暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../updater/models.js";

/**
 * ApplyUpdate 下载并应用更新（阻塞，进度通过事件推送）。
 * 二进制替换成功后：先推 done 事件让前端收尾，再由 main 注入的回调重启应用
 * （释放端口 -> 启动新进程 -> 退出旧进程）。
 */
export function ApplyUpdate(info: updater$0.UpdateInfo | null): $CancellablePromise<void> {
    return $Call.ByID(3087407177, info);
}

/**
 * CheckUpdate 检查是否有新版本
 */
export function CheckUpdate(): $CancellablePromise<updater$0.UpdateInfo | null> {
    return $Call.ByID(591332461).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * EmitUpdateAvailable 推送有可用更新事件（供 main 启动检查用）
 */
export function EmitUpdateAvailable(info: updater$0.UpdateInfo | null): $CancellablePromise<void> {
    return $Call.ByID(3167694157, info);
}

/**
 * GetCurrentVersion 当前版本号
 */
export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(2865083543);
}

/**
 * SetSkippedVersion 记录用户跳过的版本号，该版本不再提示
 */
export function SetSkippedVersion(version: string): $CancellablePromise<void> {
    return $Call.ByID(2585475084, version);
}

// Private type creation functions
const $$createType0 = updater$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
