// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LogEntry {
    "id": string;

    /**
     * "15:04:05"
     */
    "timestamp": string;

    /**
     * "2026-08-08 15:04:05" 精确到秒，用于持久化排序
     */
    "dateTime": string;

    /**
     * "2026-08-08" 用于按天查
     */
    "date": string;
    "model": string;

    /**
     * auto 模式下实际用到的模型
     */
    "usedModel"?: string;

    /**
     * 请求来源（从 User-Agent 推断：Claude Code/Codex/Benchmark/curl...）
     */
    "source"?: string;
    "upstream": string;

    /**
     * "success" | "error" | "auth_error" | "fallback"
     */
    "status": string;
    "code": number;

    /**
     * ms
     */
    "duration": number;
    "errorMsg"?: string;

    /**
     * 详细字段（持久化用，前端展开查看）
     * "POST"
     */
    "method"?: string;

    /**
     * "/v1/messages"
     */
    "path"?: string;

    /**
     * 是否流式请求
     */
    "stream"?: boolean;

    /**
     * 请求体
     */
    "requestBody"?: string;

    /**
     * 响应体
     */
    "responseBody"?: string;

    /**
     * 用量/费用字段
     * 输入 token
     */
    "inputTokens"?: number;

    /**
     * 输出 token
     */
    "outputTokens"?: number;

    /**
     * 命中缓存的输入 token
     */
    "cacheHitTokens"?: number;

    /**
     * 本次费用（美元）
     */
    "cost"?: number;

    /**
     * 费率说明（如 "$1.40/M 入 / $4.40/M 出"）
     */
    "costText"?: string;

    /**
     * 响应里真实使用的模型
     */
    "realModel"?: string;

    /**
     * 首字节用时（ms，伪流式下 ≈ 总用时）
     */
    "firstByteMs"?: number;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("dateTime" in $$source)) {
            this["dateTime"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

/**
 * ModelRef 配置中的模型引用（类型别名，避免循环引用 config 包）
 */
export class ModelRef {
    "upstream": string;
    "model": string;

    /** Creates a new ModelRef instance. */
    constructor($$source: Partial<ModelRef> = {}) {
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelRef($$parsedSource as Partial<ModelRef>);
    }
}

export class ProxyStatus {
    "running": boolean;
    "port": number;
    "host": string;

    /**
     * "auto" | "manual"
     */
    "mode": string;
    "requests": number;

    /** Creates a new ProxyStatus instance. */
    constructor($$source: Partial<ProxyStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("requests" in $$source)) {
            this["requests"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyStatus($$parsedSource as Partial<ProxyStatus>);
    }
}
